# List of words for the mole game (most AI generated)
# Consider making an fetch request from AI to generate new word each time instead of using list?

word_list = [
    "Jungle",
    "Beach",
    "Space",
    "Boat",
    "Office",
    "North Pole",
    "Hospital",
    "Cinema",
    "Forest",
    "Restaurant",
    "Mountains",
    "Zoo",
    "Farm",
    "Mall",
    "School",
    "Park",
    "Library",
    "Airport",
    "Stadium",
    "Castle",
    "Aquarium",
    "Museum",
    "Factory",
    "Concert Hall",
    "Subway Station",
    "Island",
    "Canyon",
    "Desert",
    "Pub",
    "Café",
    "Bank",
    "Grocery Store",
    "Hotel",
    "Warehouse",
    "Garage",
    "Laboratory",
    "Theater",
    "Playground",
    "Gym",
    "Salon",
    "Spa",
    "Bus",
    "Airplane",
    "Jurassic Park"
]